# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-ca'
baseurl: /
# Website info
title: Ryan Choi
description: Professional digital marketing and search-engine optimization services.
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.ico
favicon: assets/images/favicon.ico
# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: tryghost # replace by your username
facebook: ghost # replace by your username
# Disqus
disqus: False
disqus_shortname: jekyller # replace with your disqus username
# Google Analytics
google_analytics: UA-69281367-1 # replace with your GA tracking identifier
# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag
# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`
# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]
feed:
  path: feed.xml
exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
